process_nd2:
  colors:
  fovs:
    - 0
    - 2
    - 9
  xcrop: [128, 2431]
  ycrop: [108, 2051]

preprocess_images:
  invert: [2]
  bg_subtract: True
  bg_size: 200

# um/px: 0.11
segmentation:
  channel: 2
  method: bounding_box
  estimator_params:
    bounding_box:
      acut: 0.8
      aratio_min: 2.5
      aratio_max: 100
      h0: 20
      h1: 200
      w0: 8.5
      w1: 10.5
      border_pad: 5
      threshold:
  mask_params:
    threshold: 0.95

collection:
  # normally the px2um is saved in the metadata.txt file
  px2um: null
  crops:
    pad_x: 5
    pad_y: 5

dimensions:
  bins:
    - 32
    - 16
    - 32
    - 32
  units_dx:
    - 2
    - 0.1
    - 2
    - 2
  mode: um

dimensions_other:
  bins:
    - 32
    - 32
  units_dx:
    - 2
    - 0.1

